#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

DB="pg-functions-test"
dropdb "$DB" || true
createdb "$DB"
psql -v ON_ERROR_STOP=1 "$DB" < ./postgres-functions.sql
psql "$DB" < tests.sql > /tmp/pg-functions-test-output 2>&1
diff -u /tmp/pg-functions-test-output tests-expected

